# HSV thresholds
wheel_thresh: [100, 175, 0, 115, 255, 255]
spigot_thresh: [100, 175, 0, 115, 255, 255]
shuttlecock_thresh: [100, 175, 0, 115, 255, 255]
switch_thresh: [0, 27, 165, 255, 100, 255]
wheel_thresh2: [0, 0, 0, 255, 255, 50] # For black tape on wheel
spigot_thresh2: [0, 0, 0, 0, 0, 0] # TODO: For green fiducial on spigot, if necessary
shuttlecock_thresh2: [0, 0, 175, 255, 75, 255] # For white pipes around shuttlecock
